tasks:
  - init: echo "Replace me with a build script for the project."
    command: cd maple-syrup && npm install
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000

vscode:
  extensions:
    - mathisonian.idyll-syntax@0.0.2:ejwk70Ciu31IzGIZBKLnGQ==